[package]
name = "nwtzui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
tokio = {version =  "1.42.0", features = ["fs"] }
iced = { version = "0.13.1", features = ["highlighter", "tokio", "debug"]}
rfd = "0.15.3"
chrono = "0.4.40"
